### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [ivan-pi/FC8#8]
I suggest adding the topics `chip8`, `chip-8`, `interpreter` in the About section.  I had never heard of chip-8 before seeing your project, but each of the those topics has hundreds of matches.

**Comment by ivan-pi** [comment]
Done. Yes, I took the dive and wrote yet another CHIP-8 interpreter. But I am not aware of any other ones in Fortran. (This was also my motivation for opening the thread: https://fortran-lang.discourse.group/t/emulators-and-interpreters-in-fortran/5042).
